In [1]:
import math

In [2]:
a = 16
print(math.sqrt(a))

4.0


In [4]:
from math import sqrt, sin

In [5]:
a = 16
b = 3.14
print(math.sqrt(a))
print(math.sin(b))

4.0
0.0015926529164868282


In [15]:
a = 25
b = 1.7
print(math.sqrt(a))
print(math.sin(b))

5.0
0.9916648104524686


In [22]:
import numpy as np
# Numbers for which square root wil be calculated
np_sqrt = np.sqrt([2,4,9,16])

In [24]:
# Square root values
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

 ### Trigonometric Functions

In [25]:
# import pi*
from numpy import pi
np.cos(0)

1.0

In [27]:
np.sin(pi/2)

1.0

In [28]:
np.cos(pi)

-1.0

In [29]:
# Return the floor of the input element wise
np.floor([1.5, 1.6, 2.7, 3.3, 1.1, -0.3, -1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [30]:
# Exponential functions for complex mathematical calculations
np.exp([0, 1, 5])

array([  1.        ,   2.71828183, 148.4131591 ])

### Shape Manipulation

In [32]:
new_cyclist_trials = np.array([[10, 15,17,26,13,19], [12, 11, 21, 24, 14, 23]])

In [33]:
# Flattens the dataset
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [37]:
# Changes or reshapes the dataset to 3 rows and 4 columns
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [38]:
# resizes again to 2 rows and 6 columns
new_cyclist_trials.resize(2,6)

In [39]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [48]:
# Splits the array into two
np.hsplit(new_cyclist_trials, 2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [49]:
new_cyclist_1 = np.array([10, 15, 17,26,13,19])

In [51]:
new_cyclist_2 = np.array([12, 11, 21, 24, 14, 13])

In [52]:
# Stacks the arrays together
np.hstack((new_cyclist_1, new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 13])

In [1]:
import numpy as np

In [2]:
np.array(24)

array(24)

In [4]:
# oneD array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
# twoD array
np.array([[1,1,1], [2,2,2]])

array([[1, 1, 1],
       [2, 2, 2]])

In [6]:
# threeD array
np.array([[[1,1,1,1], [2,2,2,2]], [[3,3,3,3], [4,4,4,4]]])

array([[[1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[3, 3, 3, 3],
        [4, 4, 4, 4]]])

In [7]:
numpy_arr = np.array([[[1,1,1,1], [2,2,2,2]], [[3,3,3,3], [4,4,4,4]]])

In [8]:
# check shape
numpy_arr.shape

(2, 2, 4)

In [9]:
# check dimention
numpy_arr.ndim

3

### Shape and axis

In [10]:
import numpy as np

In [12]:
numpy_arr = np.array([x for x in range(1,10)])

In [13]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# convert oneD array into threeD array
numpy_arr = np.array([x for x in range(1, 13)])

In [16]:
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
# we can modifiy (3,2,2)
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
numpy_arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
numpy_arr = numpy_arr.reshape(3,2,2)

In [21]:
numpy_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
numpy_arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])