In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(10)])

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# even or odd
np.where(x%2==0, 'Even', 'Odd')


array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [5]:
# conditon list or choise list
condlist = [x<5, x>5]
choiselist = [x**2, x**3]

In [6]:
np.select(condlist,choiselist, default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

### Common Mathematical and Statistical Functions in NumPy

In [8]:
import numpy as np

In [9]:
arr = np.array([[4,3,2], [10,1,0], [5,8,24]])

In [10]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [12]:
# passing the minimum value in the array
np.amin(arr)

0

In [14]:
# axis 0 will give vertical and axis 1 will give horizontal
np.amin(arr, axis=0)

array([4, 1, 0])

In [15]:
np.amin(arr, axis=1)

array([2, 0, 5])

In [16]:
# we have a max function will give maximum value in the array
np.max(arr)

24

In [17]:
# amax for axis max
np.amax(arr, axis=0)  # will give vertical axis

array([10,  8, 24])

In [18]:
# amax for axis max
np.amax(arr, axis=1)  # will give Horizontal axis

array([ 4, 10, 24])

In [19]:
# will give median value
np.median(arr)

4.0

In [20]:
# will give mean value
np.mean(arr)

6.333333333333333

In [21]:
# std will give Stander deviation
np.std(arr)

6.944222218666553

In [22]:
# var will give Varience value
np.var(arr)

48.22222222222222

In [24]:
# we can also look at percentail value 
# we need to know the value 48. percentail
np.percentile(arr, 50)

4.0

In [25]:
# give numpy in degree
deg = np.array([0, 30, 45, 60, 90])

In [26]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [27]:
# we can also use cosin or tan method
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [28]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [29]:
# to find the inverce trigonometric function by the help of 
'''
arcsin
arccos
arctan
'''


'\narcsin\narccos\narctan\n'

In [30]:
arr = np.array([0.1, 0.8, -2.2, -9.87])

In [31]:
# floor will give floor value
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [32]:
# ceil value
np.ceil(arr)

array([ 1.,  1., -2., -9.])