In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3], [4,5,6]])
array_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

In [3]:
array_1d[0]

1

In [4]:
array_1d[1]

2

In [5]:
array_1d[-3]

4

In [6]:
array_1d[2]

3

In [7]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array_2d[0,0]

1

In [9]:
array_2d[0,1]

2

In [10]:
array_2d[0,2]

3

In [11]:
array_2d[0,-1]

3

In [12]:
array_2d[1,-1]

6

In [13]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
array_3d[0,1,2]

6

In [15]:
array_3d[1,1,-1]

12

In [22]:
# [1,0,0] ==> 1 will return 3D array of 2nd array & 0,0 is index of 3d array
array_3d[1,0,0]

7

In [24]:

# [0,0,0] ==> 0 will return 3D array of 1nd array & 0,0 is index of 3d array
array_3d[0,0,0]

1

In [25]:
array_3d[1,1,-1]

12

In [27]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [26]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [28]:
# slice 3rd index to 5th index
array_1d[3:5]

array([4, 5])

In [29]:
# slice 3rd index to 5th index
array_1d[-3:-1]

array([4, 5])

In [30]:
# slice 2d array
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_2d[1,1:]

array([5, 6])

In [33]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

In [35]:
# slice 3d array
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
array_3d[0,1:,1:]

array([[5, 6]])