### <center><u><strong>Problem Statement</strong></u></center>

Create a one-dimension array with alias s np and perform the following methods:
<ol>
    <li>np.Zeros()</li>
    <li>np.once()</li>
    <li>np.empty()</li>
    <li>np.arange()</li>
    <li>np.reshape()</li>
    <li>np.linspace()</li>
</ol>


In [1]:
# import NumPy library
import numpy as np

In [5]:
# First NumPy array
first_numpy_array = np.array([1,2,3,4]) 
# Reular array: Mention array elements within square brackets

In [6]:
# print first array
print(first_numpy_array)

[1 2 3 4]


In [26]:
# Array with zeros
array_with_zeros = np.zeros((3,3))
# Zeros array: Mentions shape of array within parentheses
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[3.56035924e-307, 2.78146116e-307, 2.22517741e-307],
       [4.45040236e-307, 1.33508251e-307, 2.11396446e-307]])

In [14]:
# array with arange method 
np_arange = np.arange(12)

In [15]:
# print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
# reshape method to change/ create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
# linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(1,6,5)

# first element = 1
# last element = 6
# Total number of equidistant elements = 5

In [18]:
# print linespaced array
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [19]:
# One dimensional array
oneD_array = np.arange(15)

In [20]:
# print 1D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
# Two dimensional array
TwoD_array = oneD_array.reshape(3,5)

In [22]:
# print 2D array
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
# Three dimensional array
ThreeD_array = np.arange(27).reshape(3,3,3)

In [24]:
# print 3D array
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
